# Generated by Django 4.2.2 on 2023-07-16 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TechGearXapp', '0003_cart_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='user',
            new_name='author',
        ),
    ]
